POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZjY4ZTgzMjU4YmViMDE4NjVkMjBlYSIsImlhdCI6MTY5NTU1NDIyMCwiZXhwIjoxNjk1NTU3ODIwfQ.6ovPzIqhk_WRPljr1HiZUuzKkXcNwi1enMYxezNF0XI

{
    "title": "Test2222",
    "author": "Superuser",
    "url": "http://localhost:3003",
    "likes": 100
}